export const metadata = {
  title: "JSXSquad team",
  description: "Generated by Next.js",
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}): React.ReactNode => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
