import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "@/assets/styles/main.scss";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import StoreProvider from "../StoreProvider";

export const metadata = {
  title: "JSXSquad team",
  description: "Generated by Next.js",
};

const RootLayout = async ({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}): Promise<React.ReactNode> => {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <StoreProvider>
          <NextIntlClientProvider messages={messages}>
            <Header />
            <main className="main">{children}</main>
            <Footer />
          </NextIntlClientProvider>
        </StoreProvider>
      </body>
    </html>
  );
};

export default RootLayout;
