import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "@/assets/styles/main.scss";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import { Providers } from "./Providers";
import { cookies } from "next/headers";
import { SESSION_COOKIE_NAME } from "@/constants/constants";

export const metadata = {
  title: "JSXSquad team",
  description: "Generated by Next.js",
};

const RootLayout = async ({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}): Promise<React.ReactNode> => {
  const messages = await getMessages();
  const session = cookies().get(SESSION_COOKIE_NAME)?.value || null;

  return (
    <Providers>
      <html lang={locale}>
        <body>
          <NextIntlClientProvider messages={messages}>
            <Header session={session} />
            <main className="main">{children}</main>
            <Footer />
          </NextIntlClientProvider>
        </body>
      </html>
    </Providers>
  );
};

export default RootLayout;
